### ISSUE TITLE
Possible problem with mlcp and 10.0-2

### ISSUE THREAD

**Issue by mariannemyers** [marklogic-community/grove-ml-gradle#10]
I could not load the sample data with 10.0-2.  Adding a placeholder ticket and assigning to me to follow back up on this.

**Comment by grtjn** [comment]
It is important to keep mlcp dependency version equal or higher than ML version. Running mlcp 9 against ml 10 might indeed break. We ought to update the default dependencies to very latest..

**Comment by grtjn** [comment]
Fixed in dev
