### ISSUE TITLE
Move over ml-content to ml-data, to follow suite with ml-gradle's mlLoadData task and remove other OBE tasks

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-ml-gradle#19]
Allows dropping mlLoadContent task as well. Use collections.properties to assign a config collection to those docs..

**Comment by mariannemyers** [comment]
Remove mlLoadContent in build.gradle.

**Comment by mariannemyers** [comment]
Also remove setSchemasPermissions and setModulesPermissions tasks.  Also root/admin/fix-permissions.xqy.

**Comment by mariannemyers** [comment]
Also rename ml-modules to ui-modules and add the appropriate property to gradle.properties.  Also for ui-data.  Examples:

`mlModulePaths=src/main/ml-modules,src/main/ui-modules`
`mlDataPaths=src/main/ml-data,src/main/ui-data`

src/main/ml-modules and src/main/ml-data don’t necessarily have to exist.. ignored silently if they are missing
