### ISSUE TITLE
Load content fails with latest java

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-ml-gradle#20]
You might see something like this using Java 10 or 12:

> Task :mlLoadContent
20/04/16 10:58:29 INFO contentpump.LocalJobRunner: Content type is set to MIXED. The format of the inserted documents will be determined by the MIME type specification configured on MarkLogic Server.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/Users/poneill/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-auth/2.6.0/b0b8dec23a84ac8a0d00fbd69a87d320724ae34a/hadoop-auth-2.6.0.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/04/16 10:58:30 INFO contentpump.ContentPump: Job name: local_1708497191_1
20/04/16 10:58:30 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 2
20/04/16 10:58:30 ERROR contentpump.LocalJobRunner: Error checking output specification: 
20/04/16 10:58:30 ERROR contentpump.LocalJobRunner: java.lang.IllegalArgumentException: No enum: segment

**Comment by grtjn** [comment]
Make sure to use latest ml-gradle and mlcp when using recent Java. We are bumping versions in development branch, but that hasn't landed in master yet.

Latest ml-gradle is currently 4.0.1, which ought to work:

https://github.com/marklogic-community/grove-ml-gradle/blob/master/build.gradle#L11

Latest mlcp is currently 10.0.4:

https://github.com/marklogic-community/grove-ml-gradle/blob/master/build.gradle#L28

Edit the versions in build.gradle, and rerun your gradle command.

**Comment by mariannemyers** [comment]
Confirmed working with Java 11, ml-gradle to 4.0.3 and mlcp to 10.0.4.
