### ISSUE TITLE
mlDeployApp Failing "Unable to copy file to string from path"

### ISSUE THREAD

**Issue by sjordan1975** [marklogic-community/grove-ml-gradle#5]
Using latest grove build on Mac OS, following command errors

// from inside marklogic dir
`./gradlew mlDeploy`

Error:
> Unable to copy file to string from path: /Users/sjordan/.gradle/daemon/4.8/./ml-config/security/roles/app-role.json; cause: /Users/sjordan/.gradle/daemon/4.8/./ml-config/security/roles/app-role.json (No such file or directory)

Work around is to use --no-daemon flag
`./gradlew --no-daemon mlDeploy`

**Comment by rjrudin** [comment]
This is likely due to using Gradle 4 or 5 and Java 11 together; try upgrading to ml-gradle 3.12.0 to fix this - https://github.com/marklogic-community/ml-gradle/releases/tag/3.12.0

**Comment by grtjn** [comment]
Alternatively, run that project with an older Java. Different versions can usually co-exist, and you can use JAVA_HOME to tell which to use.

**Comment by grtjn** [comment]
ml-gradle dependency is upgraded in dev. Note though that if you replace this gradle part with DHF, you might hit the same issue there..
